// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAvatarURL holds the string denoting the avatar_url field in the database.
	FieldAvatarURL = "avatar_url"

	// EdgeNamespaces holds the string denoting the namespaces edge name in mutations.
	EdgeNamespaces = "namespaces"
	// EdgeOwnedNamespaces holds the string denoting the owned_namespaces edge name in mutations.
	EdgeOwnedNamespaces = "owned_namespaces"

	// Table holds the table name of the user in the database.
	Table = "users"
	// NamespacesTable is the table the holds the namespaces relation/edge. The primary key declared below.
	NamespacesTable = "namespace_members"
	// NamespacesInverseTable is the table name for the Namespace entity.
	// It exists in this package in order to avoid circular dependency with the "namespace" package.
	NamespacesInverseTable = "namespaces"
	// OwnedNamespacesTable is the table the holds the owned_namespaces relation/edge. The primary key declared below.
	OwnedNamespacesTable = "namespace_admins"
	// OwnedNamespacesInverseTable is the table name for the Namespace entity.
	// It exists in this package in order to avoid circular dependency with the "namespace" package.
	OwnedNamespacesInverseTable = "namespaces"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldAvatarURL,
}

var (
	// NamespacesPrimaryKey and NamespacesColumn2 are the table columns denoting the
	// primary key for the namespaces relation (M2M).
	NamespacesPrimaryKey = []string{"namespace_id", "user_id"}
	// OwnedNamespacesPrimaryKey and OwnedNamespacesColumn2 are the table columns denoting the
	// primary key for the owned_namespaces relation (M2M).
	OwnedNamespacesPrimaryKey = []string{"namespace_id", "user_id"}
)
