// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Namespace is the predicate function for namespace builders.
type Namespace func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
